# Config Version. Pls do not change this!
config-version = "1.0"

# The Prefix of this Plugin
prefix = "<gradient:light_purple:dark_purple>VEssentials <gray>>>"

# Message when you don´t have the Permission for something
noperms = "%plugin_prefix% <red>You don´t have the Permission to perform that Command!"

# Message if the action needs you to be a Player
nocons = "%plugin_prefix% <red>You have to be a Player to perform that Command!"

# The to few and to many Arguments Messages
ToFewArgs = "%plugin_prefix% <red>You provided to few Arguments!"
ToManyArgs = "%plugin_prefix% <red>You gave to many Arguments!"

# The ban and kick Message when you get banned/kicked
banmessage = [ "<dark_gray>-------------------------------", " ", "<dark_gray>You got <dark_blue><b>banned <reset><dark_gray>by <dark_gray><b>%player_name%", " ", "<dark_gray>reason: <dark_blue><b>%player_banned_reason%", " ", "<dark_gray>duration: <dark_blue><b>%player_banned_time%", " ", "<dark_gray>------------------------------" ]
kickmessage = [ "<dark_gray>-------------------------------", " ", "<dark_gray>You got <dark_blue><b>kicked <reset><dark_gray>by <dark_gray><b>%player_name%", " ", "<dark_gray>reason: <dark_blue><b>%player_kicked_reason%", " ", "<dark_gray>------------------------------" ]

# Change the Motd here
motdline1 = " <gray>-<dark_gray>*<gray>-<dark_gray>*<gray>-<dark_gray>*<gray>-<dark_gray>*<gray>- <dark_blue><b>The Example Network <reset><gray>-<dark_gray>*<gray>-<dark_gray>*<gray>-<dark_gray>*<gray>-<dark_gray>*<gray>-"
motdline2 = " <dark_gray><b>| <reset><dark_blue> Sub Line  <dark_gray><b>| <dark_blue>  mc.example.com    <dark_gray><b>| <reset><dark_blue>Sub Line <dark_gray><b>|"

# Change MaintenanceMotd here
MaintenanceMotd1 = "   <gray>-<dark_gray>*<gray>-<dark_gray>*<gray>-<dark_gray>*<gray>-<dark_gray>*<gray>- <dark_blue><b>The Example Network <reset><gray>-<dark_gray>*<gray>-<dark_gray>*<gray>-<dark_gray>*<gray>-<dark_gray>*<gray>-"
MaintenanceMotd2 = " <dark_gray><b>| <reset><red>Maintenance<dark_gray><b> |<dark_blue> mc.example.com <dark_gray><b>| <reset><red>Maintenance<dark_gray><b> |"

# Enable/Disable the GlobalTablist here
tablist = true

# Set the Global Tablist here
header = [ "<dark_gray><st>                              <reset><dark_gray>[<dark_blue><b>Example<reset><dark_gray>]<st>                            ", "<dark_gray>Welcome <dark_blue>%player_name% <dark_gray>on <dark_blue>mc.example.net" , " ", "<dark_gray>You´re currently connected to <dark_blue>%player_server%" ]
footer = [" <dark_gray>Time: <dark_blue>%sytem_time%", "<dark_gray>You´re Ping: <dark_blue>%player_ping%", "<dark_gray>Discord: <dark_blue>discord.example.com", "<dark_gray><st>                              <reset><dark_gray>[<dark_blue><b>Example<reset><dark_gray>]<st>                            " ]

# The Message announced 30min, 10min, 1min and <10sec before Restarts
restart-message = "<dark_gray><st>                         <reset><dark_gray>[<dark_blue><b>Restart<dark_gray>]<st>                         \n \n&8The Proxy is restarting in &1%Restarttime% <newline><newline> <dark_gray><st>                              <reset><dark_gray>[<dark_blue><b>Restart<dark_gray>]<st>                              "

# The kick message when the Server is restarting
restart-kick = [ "<dark_gray>-------------------------------", " ", "<dark_gray>You got <dark_blue><b>kicked <reset><dark_gray>because of a <dark_blue><b>restart", " ", "<dark_gray>Reason: <dark_blue><b>%Reason%", "<dark_gray>Restarter: <dark_blue><b>%player_name%" ," ", "<dark_gray>------------------------------" ]

# The maintenance message
maintenance = [ "<dark_gray><b>>> <dark_blue>mc.example.com <dark_gray><b><<", "<gray>This network is currently under maintenance", " ", "<dark_gray>Reason: <dark_blue>%Reason%", " ", "<dark_gray>You want to contact us?", "<dark_gray>Discord >> <dark_blue>discord.example.com", "<dark_gray>Homepage >> <dark_blue>www.example.com" ]

# The JoinMe Message
joinme = [ "<dark_gray><st>                    <reset><dark_gray>[<dark_blue><b>JoinMe<reset><dark_gray>]<st>                    ", "<dark_blue><b>%player_name% <reset><dark_gray>is playing on <dark_blue><b>%player_server%", "<dark_gray>Click here to join", "<dark_gray><st>                    <reset><dark_gray>[<dark_blue><b>JoinMe<reset><dark_gray>]<dark_gray><st>                    "]